SET(HMCSA_VERSION 0.0.1)
SET(HMCSA_MAJOR_VERSION 0)
SET(HMCSA_MAJOR_MINOR_VERSION 000001)
SET(HMCSA_VERSION_STRING "0.0.1 (Dev)")
SET(HMCSA_ENABLE_DEVELOPMENT_MODE_DEFAULT ON) # Change to 'OFF' for a release
